#!/usr/bin/env bash

# padding
# don't want padding
# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# config
yabai -m config layout bsp
# yabai -m config auto_balance off
# yabai -m config split_ratio 0.5
# yabai -m config window_shadow off

yabai -m config mouse_follows_focus on
yabai -m mouse_drop_action swap

# list of apps for yabai to ifnore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Finder$" manage=off
