#!/usr/bin/env bash

# padding
# don't want padding
# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# config
yabai -m config layout bsp
yabai -m config auto_balance on
# yabai -m config split_ratio 0.5
# yabai -m config window_shadow off

yabai -m config mouse_follows_focus on
yabai -m mouse_drop_action swap

# list of apps for yabai to ifnore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Github Desktop$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

# Override gaps for space 2 only
yabai -m config --space 2 window_gap 0

