name: Run Ubuntu Setup Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ubuntu_versions:
        description: 'Comma-separated Ubuntu versions to use (e.g., 18.04, 20.04, 22.04, latest)'
        required: false
        default: '18.04,20.04,22.04,latest'

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: ${{ fromJson('["18.04", "20.04", "22.04", "latest"]') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Script in Docker
        run: |
          UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          docker run --rm -it \
            -v "$(pwd)/ubuntu-setup.sh:/tmp/ubuntu-setup.sh" \
            --entrypoint /bin/bash ubuntu:$UBUNTU_VERSION -c \
            "apt-get update && apt-get install -y curl sudo && chmod +x /tmp/ubuntu-setup.sh && /tmp/ubuntu-setup.sh"

